#!/bin/sh

. installation_dirs.conf

wx_flags=`./wx-config --cxxflags --libs`

include_dir=${project_directory}/include
src_dir=${project_directory}/src

clang++ -g -Wall ${wx_flags} -std=c++20 -I/${include_dir} ${src_dir}/*.cpp -o RemoteViewer