#!/bin/sh

# Read config file
. installation_dirs.conf

project_directory=`pwd`

cd ${dependency_install_directory}

# Install dependencies
# Boost
curl -LO https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.bz2
tar -xvjf boost_1_79_0.tar.bz2

# # wxWidgets
curl -LO https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.0/wxWidgets-3.2.0.tar.bz2
tar -xvjf wxWidgets-3.2.0.tar.bz2

# Build wxWidgets
cd wxWidgets-3.2.0
mkdir ${wxWidgets_build_directory_relative_path}
cd ${wxWidgets_build_directory_relative_path}
../configure --enable-debug
make

cp wx-config ${project_directory}